apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-pod-1
  namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name:  nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - name: nginx-pod-volume
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: nginx-pod-volume
    projected:
      defaultMode: 0755
      sources:
      - secret:
          name: account
          items:
            - key: user
              path: index.html
