apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    #targetPort: 80
    nodePort: 30030
  selector:
      app: nginx
      #  sessionAffinity: nginx-pod-2
